variables:
    name: "doublewell"
    variant: "v001"

data:
    path: "data/doublewell/doublewell.npz"
    chunk_size: 300
    batch_size: 16
    subsample: 1
    use_vars: [0]

model:
    model: "dsrn"
    n_states:   8
    n_guiding:  7
    stoch_vars: 1
    n_obs: 1
    n_samples:  4
    olv: -2.
    glv:  0.
    n_ignore: 50
    guiding_encoder:
        n_channels:  24
        n_levels:     7
        kernel_size:  7
    causal_encoder:
        n_channels: 24
        n_levels:    7
        kernel_size: 7
        causal: 1        
    noise_encoder:
        n_channels: 24
        n_levels:    7
        kernel_size: 7
        rnn_size: 32
    f:
        arch: 'mlptanh'
        hidden_size: 256
        alpha: 1.
        slv: -8.
        slv_trainable: True
    g:
        type: 'nonlinear'
        readout: 'det'
        n_hidden: 32

    lambda_x: 0.01
    lambda_g: 0.3
    lambda_z: 0.0


training:
    seed: 42
    n_iter: 30000
    learning_rate: 0.001
    forcing_interval: 40
    gradient_clip: 100.
    lr_milestones: [1000, 10000, 20000]
    lr_gamma: 0.3


output:
    plot_every: 5000
    save_every: 5000    
    logfile:    run/{name}/{variant}/log.txt
    plot_direc: run/{name}/{variant}/img/
    save_direc: run/{name}/{variant}/models/
